Repository fbpic/fbpic, pull requests merged in 2018-10, with the labels that each got.

#297 Fix cubic CPU deposition
  fbpic/particles/deposition/threading_methods.py
  tests/test_cpu_gpu_deposition.py
Labels: bug, cpu

#299 Fix precision limitation for flattened gaussian
  fbpic/lpa_utils/laser/laser_profiles.py
Labels: enhancement

#302 Correct Gouy phase of Laguerre-Gaussian modes
  fbpic/lpa_utils/laser/laser_profiles.py
  tests/test_flattenedgauss_laser.py
Labels: bug

#268 Add the possibility to use several passes of smoothing, and a compensator.
  docs/source/api_reference/api_reference.rst
  docs/source/api_reference/smoothing.rst
  fbpic/fields/cuda_methods.py
  fbpic/fields/fields.py
  fbpic/fields/numba_methods.py
  fbpic/fields/smoothing.py
  fbpic/fields/spectral_grid.py
  fbpic/fields/utility_methods.py
  fbpic/main.py
Labels: enhancement

#305 Close #304: Allow changing checkpoint saving folder
  fbpic/openpmd_diag/checkpoint_restart.py
  tests/test_example_docs_scripts.py
Labels: enhancement
