Repository fbpic/fbpic, pull requests merged in 2018-07, with the labels that each got.

#281 Minor updates to the documentation and safe-guards
  docs/source/overview.rst
  fbpic/main.py
Labels: documentation

#279 Avoid recompilation when threading is disabled
  fbpic/utils/threading.py
Labels: enhancement

#272 New modified Vay pusher for the envelope model
  fbpic/fields/cuda_methods.py
  fbpic/fields/fields.py
  fbpic/lpa_utils/laser/direct_envelope_injection.py
  fbpic/lpa_utils/laser/laser_profiles.py
  fbpic/main.py
  fbpic/particles/gathering/cuda_methods.py
  fbpic/particles/gathering/inline_functions.py
  fbpic/particles/gathering/threading_methods.py
  fbpic/particles/particles.py
  fbpic/particles/push/cuda_methods.py
  fbpic/particles/push/numba_methods.py
  tests/test_linear_wakefield_envelope.py
  tests/test_particle_envelope.py
Labels: enhancement, laser envelope

#285 Reduce duplication for the Vay pusher on CPU and GPU
  fbpic/particles/push/cuda_methods.py
  fbpic/particles/push/inline_functions.py
  fbpic/particles/push/numba_methods.py
Labels: cpu, gpu, refactoring

#288 Enable user to set a maximum ionisation level
  fbpic/particles/elementary_process/ionization/ionizer.py
  fbpic/particles/particles.py
  tests/test_ionization.py
Labels: ionization

#287 Close #267 Per-species density diagnostic
  docs/source/api_reference/diagnostics.rst
  docs/source/example_input/ionization_script.py
  fbpic/lpa_utils/bunch.py
  fbpic/main.py
  fbpic/openpmd_diag/__init__.py
  fbpic/openpmd_diag/field_diag.py
  fbpic/openpmd_diag/generic_diag.py
  fbpic/openpmd_diag/particle_density_diag.py
Labels: enhancement, openPMD output

#289 Fix space-charge fields for high-energy bunch with emittance
  fbpic/lpa_utils/bunch.py
Labels: bug
