Repository fbpic/fbpic, pull requests merged in 2018-06, with the labels that each got.

#274 Synchronize the laser envelope branch with the current `dev` branch
  CHANGELOG.md
  docs/source/api_reference/lpa_utilities/laser.rst
  docs/source/api_reference/lpa_utilities/laser_profiles/donut_laguerre.rst
  docs/source/images/cylindrical_grid.png
  docs/source/install/install_lawrencium.rst
  fbpic/__init__.py
  fbpic/boundaries/field_buffer_handling.py
  fbpic/lpa_utils/bunch.py
  fbpic/lpa_utils/laser/__init__.py
  fbpic/lpa_utils/laser/antenna_injection.py
  fbpic/lpa_utils/laser/direct_envelope_injection.py
  fbpic/lpa_utils/laser/direct_injection.py
  fbpic/lpa_utils/laser/laser.py
  fbpic/lpa_utils/laser/laser_profiles.py
  tests/test_laser.py
  tests/test_laser_antenna.py
  tests/test_laser_envelope.py
  tests/test_space_charge.py
Labels: laser envelope

#275 Enable restart for arbitrary modes
  fbpic/openpmd_diag/checkpoint_restart.py
Labels: bug

#276 Thread the function that erase charge/current buffers
  fbpic/fields/fields.py
  fbpic/fields/numba_methods.py
Labels: cpu, performance

#277 Allow the user to specify the temperature, through `add_new_species`
  fbpic/main.py
  tests/test_continuous_injection.py
Labels: enhancement

#278 enable checkpoints in particle-less simulations
  fbpic/openpmd_diag/checkpoint_restart.py
Labels: bug
