Repository fbpic/fbpic, pull requests merged in 2019-03, with the labels that each got.

#333 Prevent GPU particle communication/removal bug when all particles are in the guard cells
  fbpic/boundaries/particle_buffer_handling.py
Labels: bug, gpu

#335 Make the script `test_example_docs_scripts.py` more flexible
  tests/test_example_docs_scripts.py
Labels: automated tests

#336 Pass the diagnostic period as a physical time (instead of integer)
  fbpic/openpmd_diag/field_diag.py
  fbpic/openpmd_diag/generic_diag.py
  fbpic/openpmd_diag/particle_density_diag.py
  fbpic/openpmd_diag/particle_diag.py
Labels: openPMD output

#334 problem in example for boosted frame LWFA
  docs/source/example_input/boosted_frame_script.py
  tests/test_example_docs_scripts.py
Labels: bug, documentation

#339 Rename `BoostedDiagnostic` as `BackTransformedDiagnostic`
  docs/source/advanced/boosted_frame.rst
  docs/source/api_reference/diagnostics.rst
  docs/source/example_input/boosted_frame_script.py
  fbpic/openpmd_diag/__init__.py
  fbpic/openpmd_diag/boosted_field_diag.py
  fbpic/openpmd_diag/boosted_particle_diag.py
  tests/test_beam_focusing.py
  tests/test_boosted_particle_output.py
  tests/test_ionization.py
Labels: API, boosted-frame, documentation, openPMD output

#338 Make the example scripts explicitly visible in the online documentation
  docs/source/example_input/boosted_frame_script.rst
  docs/source/example_input/ionization_script.rst
  docs/source/example_input/lwfa_script.rst
  docs/source/how_to_run.rst
Labels: documentation

#343 Automatically update the documentation, when we update master
  .travis.yml
  deploy.sh
  deploy_key.enc
Labels: documentation
