Repository fbpic/fbpic, pull requests merged in 2019-05, with the labels that each got.

#344 Close #342 Automatically transform the external fields to the boosted frame
  fbpic/lpa_utils/external_fields.py
  fbpic/main.py
  tests/test_external_fields.py
Labels: API, automated tests, boosted-frame

#360 Fix restart with ionization on GPU
  fbpic/openpmd_diag/checkpoint_restart.py
Labels: bug, gpu

#361 Keep sorting arrays on GPU
  fbpic/openpmd_diag/checkpoint_restart.py
  fbpic/particles/particles.py
Labels: gpu, performance

#356 Replace pyculib by cupy
  fbpic/boundaries/particle_buffer_handling.py
  fbpic/fields/spectral_transform/cuda_methods.py
  fbpic/fields/spectral_transform/fourier.py
  fbpic/fields/spectral_transform/hankel.py
  fbpic/main.py
  fbpic/openpmd_diag/checkpoint_restart.py
  fbpic/particles/elementary_process/cuda_numba_utils.py
  fbpic/particles/elementary_process/ionization/ionizer.py
  fbpic/particles/particles.py
  fbpic/particles/utilities/cuda_sorting.py
  fbpic/utils/cuda.py
Labels: gpu, refactoring

#363 Update installation instructions for cupy
  .travis.yml
  README.md
  docs/source/install/install_comet.rst
  docs/source/install/install_cori_edison.rst
  docs/source/install/install_juwels.rst
  docs/source/install/install_lawrencium.rst
  docs/source/install/install_local.rst
  docs/source/install/install_summit.rst
  docs/source/install/install_titan.rst
  docs/source/install/installation.rst
  fbpic/particles/elementary_process/ionization/ionizer.py
  fbpic/utils/cuda.py
  fbpic/utils/threading.py
Labels: automated tests, documentation
