Repository fbpic/fbpic, pull requests merged in 2020-09, with the labels that each got.

#475 Fix scoping issues for external fields on the GPU
  fbpic/lpa_utils/external_fields.py
  fbpic/utils/cuda.py
Labels: bug, gpu

#479 Add install option for PICMI
  setup.py
Labels: picmi

#482 Fix incompatibility between FBPIC and numba 0.51+
  fbpic/utils/cuda.py
Labels: gpu

#483 Revert antenna to previous behavior
  fbpic/lpa_utils/laser/antenna_injection.py
Labels: boosted-frame

#473 Calculate laser antenna on the GPU
  fbpic/lpa_utils/laser/antenna_injection.py
  fbpic/lpa_utils/laser/laser.py
  fbpic/lpa_utils/laser/laser_profiles.py
  fbpic/particles/deposition/cuda_methods_unsorted.py
  fbpic/particles/deposition/numba_methods.py
  fbpic/particles/utilities/utility_methods.py
Labels: cpu, gpu, refactoring
